http {
    # Limit client body size.
    client_max_body_size SIZE;

    # Choose the port and host of each 'server'.
    server {
        listen PORT default_server;
        # Setup the server_names or not.
        server_name HOST; # not required

        # Setup routes with one or multiple of the following rules/configuration (routes wont be using "regexp"):
        location PATH {
            # Turn on or off directory listing.
            autoindex on;

            # Setup default error pages.
            error_page ERROR_CODE ERROR_PAGE_PATH;

            # Set a default file to answer if the request is a directory


            # Define a directory or a file from where the file should be searched (for example,
            # if url /kapouet is rooted to /tmp/www, url /kapouet/pouic/toto/pouet is
            # /tmp/www/pouic/toto/pouet).
            index FILE;

            # Define a list of accepted HTTP methods for the route.
            limit_except METHOD {
                deny all;
            }
        }

        location PATH {
            # Define a HTTP redirection.
            root DIRECTORY_PATH
        }

        location ~* \.php$ {
            cgi_pass CGI_ENDPOINT;
        }
    }
}

# ?=> The first server for a host:port will be the default for this host:port (that means it will answer to all the requests that don’t belong to an other server).